apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: druid
  name: druid
  namespace: druid
spec:
  endpoints:
    - port: prometheus
      interval: 10s
  jobLabel: druid
  namespaceSelector:
    matchNames:
      - druid
  selector:
    matchLabels:
      app: druid
